use "pony_test"
use "../ssh_error"

primitive \nodoc\ Tests is TestList
  fun tag tests(test: PonyTest) =>
    test(_TestErrorStrings)
    test(_TestCipherRoundtrip)
    test(_TestCipherDecryptCorrupted)
    test(_TestMacRoundtrip)
    test(_TestMacBitFlip)
    test(_TestMacKnownAnswer)
    test(_TestMacDifferentDataDiffers)
    test(_TestMpintRoundtrip)
    test(_TestChannelAcceptAndWindow)
    test(_TestChannelWindowExhausted)
    test(_TestChannelReplenish)
    test(_TestKexCurve25519SharedSecret)
    test(_TestKexCurve25519InvalidKey)
    test(_TestKexCurve25519WrongLengthKey)
    test(_TestServerConfigRejectsBadKey)
    test(_TestHostKeySignVerify)
    test(_TestHostKeySignVerifyCorrupted)
    test(_TestHostKeyPublicKeySize)
    test(_TestPacketRoundtripPlaintext)
    test(_TestPacketPadding)
    test(_TestPacketTooLarge)
    test(_TestPacketSequenceNumbers)
    test(_TestAlgoNegotiateFirstMatch)
    test(_TestAlgoNegotiateNoOverlap)
    test(_TestAlgoNegotiateIdenticalLists)
    test(_TestAlgoNegotiateDefaults)
    test(_TestWireU32Roundtrip)
    test(_TestWireStringRoundtrip)
    test(_TestWireNameListRoundtrip)
    test(_TestKexinitRoundtrip)
    test(_TestKexGenerateKexinit)
    test(_TestKexReceiveAndNegotiate)
    test(_TestKexDeriveKeys)
    test(_TestAuthMessageEncode)
    test(_TestAuthStateMachineTriesMethods)
    test(_TestAuthFailureDecode)
    test(_TestChannelOpenAndConfirm)
    test(_TestChannelDataSendWindowTracking)
    test(_TestChannelClose)
    test(_TestChannelFindByRemoteId)
    test(_TestEncryptedPacketRoundtrip)
    test(_TestEncryptedPacketCorrupted)
    test(_TestEncryptedPacketLargePayload)
    test(_TestChacha20Poly1305Roundtrip)
    test(_TestChacha20Poly1305SequenceNumberMatters)
    test(_TestChacha20Poly1305Corrupted)
    test(_TestChachaPacketRoundtrip)
    test(_TestChachaPacketCorrupted)
    test(_TestChachaPacketSequence)
    test(_TestGcmPacketRoundtrip)
    test(_TestGcmPacketCorrupted)
    test(_TestGcmPacketSequence)
    test(_TestStreamPacketRoundtrip)
    test(_TestStreamPacketCorruptedMac)
    test(_TestStreamPacketSequence)
    test(_TestStreamPacketSha512)
    test(_TestStreamPacketShortLength)
    test(_TestPubkeyVerifyValidAccepts)
    test(_TestPubkeyVerifyNoSignatureRejected)
    test(_TestPubkeyVerifyGarbageRejected)
    test(_TestPubkeyVerifyForgedSignedDataRejected)
    test(_TestPubkeyVerifyWrongSessionRejected)
    test(_TestPubkeyVerifyWrongKeyRejected)
    test(_TestIntegrationHandshake)
    test(_TestIntegrationPubkeyAuth)
    test(_TestIntegrationHostKeyReject)
    test(_TestIntegrationRekey)
    test(_TestPtyIcrnlLoneCr)
    test(_TestPtyIcrnlPreservesCrLf)
    test(_TestPtyIcrnlLoneCrReplaced)
    test(_TestPtyNoTransformWithoutIcrnl)
    test(_TestPtyIcrnlDisabledByZeroValue)
    test(_TestPtyModeParseRoundtrip)
    test(_TestPtyModeParseEmpty)

class iso _TestErrorStrings is UnitTest
  fun name(): String => "ssh_error/error_strings"

  fun apply(h: TestHelper) =>
    // Verify all error types produce non-empty strings
    h.assert_true(SshDecryptFailed.string().size() > 0)
    h.assert_true(SshMacMismatch.string().size() > 0)
    h.assert_true(SshSignatureInvalid.string().size() > 0)
    h.assert_true(SshKeyInvalid.string().size() > 0)
    h.assert_true(SshAuthRejected.string().size() > 0)
    h.assert_true(SshChannelClosed.string().size() > 0)
    h.assert_true(SshWindowExhausted.string().size() > 0)

    // Wrapping errors preserve inner context
    let inner: SshCryptoError = SshDecryptFailed
    let kex = SshKexFailed(inner)
    h.assert_true(kex.string().contains("decryption failed"))

    let open_failed = SshChannelOpenFailed(2, "connect failed")
    h.assert_true(open_failed.string().contains("connect failed"))
    h.assert_true(open_failed.string().contains("2"))
